import type { Metadata } from "next";
import { Crimson_Pro, Inter } from "next/font/google";

import "./globals.css";

import { cn } from "@/lib/utils";

const crimsonPro = Crimson_Pro({
    variable: "--font-crimson-pro",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "h-screen w-full overflow-auto scroll-smooth antialiased",
                    crimsonPro.variable,
                    inter.variable,
                )}
            >
                {children}
            </body>
        </html>
    );
}
